MemoryBlog/MemoryBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('articles/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
 urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 handler404 = 'MemoryBlog.views.handler404'

MemoryBlog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug>/', views.post_detail, name='post_detail'),
    path('subsection/<subsec_slug>/', views.post_list,  name='post_list_by_subsec'),
    path('section/<sec_slug>/', views.post_list,  name='post_list_by_sec'),
    path('section/<sec_slug>/<subsec_slug>', views.post_list,  name='post_list_by_sec_and_subsec'),
    path('author/<author>/', views.post_list,  name='post_list_by_author'),
    path('comments/<article_id>', views.add_comment, name='add_comment'),

]

MemoryBlog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from django.contrib.postgres.fields.array import ArrayField
from newsletter.models import NewsUser
from post_office import mail

# Create your models here.

class Section(models.Model):
    class Meta:
        db_table = 'section'
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

    name = models.CharField(max_length=200)
    sec_slug = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    seo_desription = models.CharField(max_length=200, blank=True)
    order_range = models.IntegerField(default=100)
    has_subsection = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Subsection(models.Model):
    class Meta:
        db_table = 'subsection'
        verbose_name = 'Подраздел'
        verbose_name_plural = 'Подразделы'

    name = models.CharField(max_length=200)
    subsec_slug = models.SlugField()
    description = models.TextField(blank=True)
    seo_desription = models.CharField(max_length=200, blank=True)
    section = models.ForeignKey(Section, on_delete=models.PROTECT)
    order_range = models.IntegerField(default=100)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Subsection, self).save(*args, **kwargs)
        subs = self.section
        if not subs.has_subsection:
            subs.has_subsection = True
            subs.save()


class Article(models.Model):
    class Meta:
        db_table = 'article'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    STATUS_CHOICE = (
        ('черновик', 'Черновик'),
        ('опубликован', 'Опубликован')
    )

    article_title = models.CharField(verbose_name='Заголовок статьи', max_length=200, default='Новая статья')
    slug = models.SlugField()
    article_description = models.TextField(max_length=200, blank=True, verbose_name='Краткое описание статьи')
    section = models.ForeignKey(Section, on_delete=models.CASCADE, verbose_name='Раздел')
    subsection = models.ForeignKey(Subsection, on_delete=models.PROTECT, blank=True, null=True, verbose_name='Подраздел')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    date = models.DateTimeField(verbose_name='Дата публикации')
    head_image = models.ImageField(upload_to='post_images/', default='post_images/None/default_image.jpg', verbose_name='Изображение в шапке')
    content = RichTextUploadingField(verbose_name='Содержание поста', config_name='default')
    status = models.CharField(verbose_name='Статус', max_length=11, choices=STATUS_CHOICE, default='черновик')
    allow_comments = models.BooleanField(verbose_name='Разрешены комментарии', default=True)

    seo_desription = models.CharField(verbose_name='СЕО-описание', max_length=140, blank=True)
    seo_title = models.CharField(verbose_name='СЕО-title', max_length=90, blank=True)
    seo_keywords = models.CharField(verbose_name='СЕО-keywords', max_length=140, blank=True)

    def __str__(self):
        return self.article_title

    def get_absolute_url(self):
        return reverse('post_detail', args=[self.slug])

    #Переопределение метода save() для рассылки уведомлений сразу после публикации новой статьи.
    def save(self, *args, **kwargs):
        super(Article, self).save(*args, **kwargs)
        if self.status == 'опубликован':
            subscribers = NewsUser.objects.all().filter(is_active=True)
            for i in subscribers:
                mail.send(
                    i.email,
                    'zoltan66@mail.ru',
                    # subject='Новая статья на "Чердаке Воспоминаний"!',
                    # message='У нас новая статья!',
                    template='new_article',
                    context={'article_title': self.article_title,
                             'article_url': 'http://127.0.0.1:8000' + self.get_absolute_url(),
                             'url_unsubscribe': 'http://127.0.0.1:8000/newsletter/unsubscribe/' + i.user_hash + '/'},
                    priority='now',
                )


class ArticleStatistic(models.Model):
    class Meta:
        db_table = 'ArticalStatistic'
        verbose_name = 'Статистика по статьям'
        verbose_name_plural = 'Статистики по статьям'

    article = models.ForeignKey(Article, verbose_name='Статья', on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now, verbose_name='Дата статистики')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.article.article_title


class Comment(models.Model):
    class Meta:
        db_table = "comments"
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    path = ArrayField(models.IntegerField())
    article_id = models.ForeignKey(Article, on_delete=models.PROTECT)
    author_id = models.ForeignKey(User, on_delete=models.PROTECT)
    content = models.TextField('Комментарий')
    pub_date = models.DateTimeField('Дата комментария', default=timezone.now)

    def __str__(self):
        return self.content[0:200]

    def get_offset(self):
        level = len(self.path) - 1
        if level > 5:
            level = 5
        return level

    def get_col(self):
        level = len(self.path) - 1
        if level > 5:
            level = 5
        return 12 - level

MemoryBlog/blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.Form):
    parent_comment = forms.IntegerField(
        widget=forms.HiddenInput,
        required=False
    )

    comment_area = forms.CharField(
        label="",
        widget=forms.Textarea
    )

MemoryBlog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Section, Article, Subsection, ArticleStatistic, Comment
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from .forms import CommentForm
from django.contrib import auth
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render_to_response
from django.template import RequestContext


# Create your views here.

def post_list(request, subsec_slug=None, sec_slug=None, author=None):
    all_posts = Article.objects.all().filter(status='опубликован').order_by('-date')
    if sec_slug and subsec_slug:
        sec = get_object_or_404(Section, sec_slug=sec_slug)
        subsec = get_object_or_404(Subsection, subsec_slug=subsec_slug)
        all_posts = all_posts.filter(section__in=[sec]).filter(subsection__in=[subsec]).filter(status='опубликован').order_by('-date')
    else:
        if subsec_slug:
            subsec = get_object_or_404(Subsection, subsec_slug=subsec_slug)
            all_posts = all_posts.filter(subsection__in=[subsec]).filter(status='опубликован').order_by('-date')
        if sec_slug:
            sec = get_object_or_404(Section, sec_slug=sec_slug)
            all_posts = all_posts.filter(section__in=[sec]).filter(status='опубликован').order_by('-date')
        if author:
            auth_post = get_object_or_404(User, username=author)
            all_posts = all_posts.filter(author__in=[auth_post]).filter(status='опубликован').order_by('-date')
    paginator = Paginator(all_posts, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html', {'page': page, 'posts': posts})

def post_detail(request, slug):
    post = get_object_or_404(Article, slug=slug)

    obj, created = ArticleStatistic.objects.get_or_create(
        defaults={
            "article": post,
            "date": timezone.now()
        },
        # При этом определяем, забор объекта статистики или его создание
        # по двум полям: дата и внешний ключ на статью
        date=timezone.now(), article=post
    )
    obj.views += 1  # инкрементируем счётчик просмотров и обновляем поле в базе данных
    obj.save(update_fields=['views'])

    comments = post.comment_set.all().order_by('path')
    next = post.get_absolute_url()

    user = auth.get_user(request)
    if user.is_authenticated:
        form = CommentForm
        return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'next': next, 'form': form})
    else:
        return render(request, 'blog/post_detail.html',
                      {'post': post, 'comments': comments, 'next': next})


@login_required
@require_http_methods(["POST"])
def add_comment(request, article_id):
    form = CommentForm(request.POST)
    article = get_object_or_404(Article, id=article_id)

    if form.is_valid():
        comment = Comment()
        comment.path = []
        comment.article_id = article
        comment.author_id = auth.get_user(request)
        comment.content = form.cleaned_data['comment_area']
        comment.save()

        # Django не позволяет увидеть ID комментария по мы не сохраним его,
        # хотя PostgreSQL имеет такие средства в своём арсенале, но пока не будем
        # работать с сырыми SQL запросами, поэтому сформируем path после первого сохранения
        # и пересохраним комментарий
        try:
            comment.path.extend(Comment.objects.get(id=form.cleaned_data['parent_comment']).path)
            comment.path.append(comment.id)
        except ObjectDoesNotExist:
            comment.path.append(comment.id)

        comment.save()

    return redirect(article.get_absolute_url())

def handler404(request, exception, template_name='404.html'):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

MemoryBlog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}
{% load blog_extras %}
{% load socialaccount %}
{% load account %}

{% block title %}{{ post.seo_title }} | Чердак воспоминаний{% endblock %}
{% block seo %}
    <meta name="keywords" content="{{ post.seo_keywords }}">
    <meta name="description" content="{{ post.seo_desription }}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="single-blog blog-details two-column">
                <div class="post-thumb">
                    <img src="{{ post.head_image.url }}" class="img-responsive" alt="">
                </div>
                <div class="post-content overflow">
                    <h1 class="post-title bold">{{ post.article_title }}</h1>
                    <h5 class="post-author">Опубликовано {{ post.date | date:"d.m.Y" }}. Автор: <a href="{% url 'post_list_by_author' post.author %}"> {{ post.author.first_name }}</a></h5>
                    <br>
                    <p>{{ post.content|safe }}</p>
                    <div class="post-bottom overflow">
                        <ul class="nav navbar-nav post-nav">
                            <li><a href="{% url 'post_list_by_sec' post.section.sec_slug %}"><i class="fa fa-book"></i>{{ post.section }}</a></li>
                            <li><a href="{% url 'post_list_by_sec_and_subsec' post.section.sec_slug post.subsection.subsec_slug %}"><i class="fa fa-tag"></i>{{ post.subsection }}</a></li>

                            <li><a href="#post-comments"><i class="fa fa-comments"></i> {% get_comments_count post.id %}</a></li>
                        </ul>
                    </div>
                    <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
                    <script src="//yastatic.net/share2/share.js"></script>
                    <div class="ya-share2" id="share-it" data-services="collections,vkontakte,facebook,odnoklassniki,twitter"></div>
                    <div class="response-area">
                        <h2 class="bold" id="post-comments">Комментарии</h2>

                        {% for comment in comments %}
                            <a name="comment-{{ comment.id }}"></a>
                            <div class="row" id="{{ comment.id }}">
                                <div class="col-md-{{ comment.get_col }} col-md-offset-{{ comment.get_offset }}">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <strong>{{ comment.author_id.get_full_name|default:comment.author_id.username }}</strong>&nbsp;&nbsp;
                                            {{ comment.pub_date }}
                                            <a href="#comment-{{ comment.id }}">#</a>
                                        </div>
                                        <div class="panel-body">
                                            <div>{{ comment.content|safe }}</div>
                                            {% if form %}<a class="btn btn-default btn-xs pull-right"
                                                            onclick="return show_comments_form({{ comment.id }})">
                                                {% bootstrap_icon "share-alt" %}&nbsp;&nbsp;Ответить</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        {% if form %}
                            <h3 id="write_comment"><a onclick="return show_comments_form('write_comment')">Написать комментарий</a></h3>
                            <form id="comment_form" action="{% url 'add_comment' post.id %}" method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                                <button type="submit" class="btn btn-primary">{% bootstrap_icon "comment" %}&nbsp;&nbsp;Комментировать</button>
                            {% endbuttons %}
                            </form>
                        {% else %}
                            <div class="panel panel-warning">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Комментарии</h3>
                                </div>
                                <div class="panel-body">
                                    Только авторизованные пользователи могут оставлять комментарии.<br>Авторизуйтесь с помощью социальных сетей: <a href="{% provider_login_url "google" method="oauth2" %}">Google</a>, <a href="{% provider_login_url "vk" method="oauth2" %}">Вконтакте</a> или <a href="{% provider_login_url "mailru" method="oauth2" %}">Mail.ru</a><br />
                                </div>
                            </div>
                        {% endif %}

                    <script>
                        function show_comments_form(parent_comment_id)
                            {
                                if (parent_comment_id == 'write_comment')
                                {
                                    $("#id_parent_comment").val('')
                                }
                                else
                                {
                                    $("#id_parent_comment").val(parent_comment_id);
                                }
                                $("#comment_form").insertAfter("#" + parent_comment_id);
                            }
                    </script>

                    </div><!--/Response-area-->
                    </div>
                            </div>
        </div>
    </div>

{% endblock %}

MemoryBlog/templates/blog/post_detail_old.html
{% extends "base2.html" %}
{% load static %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Опубликовано {{ post.date | date:"d.m.Y" }}. Автор: <a href="{% url 'post_list_by_author' post.author %}"> {{ post.author }}</a>
    </p>
    <img src="{{ post.head_image.url }}" class="img-responsive" alt="">

    {{ post.content|safe }}
    {% get_comment_count for post as comment_count %}
    {{ comment_count }} комментариев к статье оставлено.
    <br>
    Раздел: <a href="{% url 'post_list_by_sec' post.section.sec_slug %}"> {{ post.section }}</a>. Подраздел: <a href="{% url 'post_list_by_subsec' post.subsection.subsec_slug %}"> {{ post.subsection }}</a>
    {% if comment_count %}
        <hr/>
        <ul class="media-list">
          {% render_xtdcomment_tree for post %}
        </ul>
    {% endif %}

    <script
        src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
    </script>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip({html: true})
        })
    </script>

    {% if post.allow_comments %}
        <div class="comment">
          <h4 class="text-center">Ваш комментарий</h4>
          <div class="well">
            {% render_comment_form for post %}
          </div>
        </div>
    {% endif %}

    {% include 'popular.html' %}

{% endblock %}

MemoryBlog/templates/blog/post_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% load blog_extras %}
{% block title %}Всё о развитии памяти и внимания{% endblock %}
{% block headline %}Всё о развитии памяти и внимания{% endblock %}
{#{% block seo %}#}
{#    <meta name="keywords" content="{{ post.seo_keywords }}">#}
{#    <meta name="description" content="{{ post.seo_desription }}">#}
{#{% endblock %}#}
{% block content %}
    {% for post in posts %}
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="single-blog single-column">
                <div class="post-thumb">
                    <a href="{{ post.get_absolute_url }}"><img src="{{ post.head_image.url }}" class="img-responsive" alt=""></a>
                </div>
                <div class="post-content overflow">
                    <h2 class="post-title bold" id="list-post-title"><a href="{{ post.get_absolute_url }}">{{ post.article_title }}</a></h2>
                    <h5 class="post-author">Опубликовано {{ post.date | date:"d.m.Y" }}. Автор: <a href="{% url 'post_list_by_author' post.author %}"> {{ post.author.first_name }}</a></h5>
                    <p>{{ post.article_description | safe }}</p>
                    <a href="{{ post.get_absolute_url }}" class="read-more">Читать далее</a>
                    <div class="post-bottom overflow">
                        <ul class="nav navbar-nav post-nav">
                            <li><a href="{% url 'post_list_by_sec' post.section.sec_slug %}"><i class="fa fa-book"></i>{{ post.section }}</a></li>
                            <li><a href="{% url 'post_list_by_sec_and_subsec' post.section.sec_slug post.subsection.subsec_slug %}"><i class="fa fa-tag"></i>{{ post.subsection }}</a></li>
                            <li><a href="{{ post.get_absolute_url }}#post-comments"><i class="fa fa-comments"></i>{% get_comments_count post.id %}</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="blog-pagination">
        {% bootstrap_pagination posts %}
    </div>

{% endblock %}